<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ClearLend.Application\ClearLend.Application.csproj" />
    <ProjectReference Include="..\ClearLend.Infrastructure\ClearLend.Infrastructure.csproj" />
    <ProjectReference Include="..\ClearLend.Contracts\ClearLend.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
